### ISSUE TITLE
Bare bones, but too bare.

### ISSUE THREAD

**Issue by bransinanderson** [fndaily/craft-foundation-6#2]
Would be great to incorporate original output of what Foundation generates for reference. I'm talking about the index.html boilerplate that is generated on foundation build. I've created a simple foundation setup to serve as reference, but it would be nice if this were included.

I see this as bare bones and very customizable - which I like. Was there reason of removing the style guide? I would like to hear what you use as an alternative.

**Comment by JRetza** [comment]
Updated for Foundation 6.4.3

- Styleguide added
- bower removed
- ready for webpack
